export const users: ({
    objectGUID: string;
    whenCreated: number;
    whenChanged: number;
    username: string;
    firstName: string;
    name: string;
    middleName: undefined;
    language: string;
    userPassword: string;
    mail: string;
    emailVerified: boolean;
    mobile: string;
    mobileVerified: boolean;
    memberOf: string[];
    orgId: string;
    userAccountControl: number;
    pwdLastSet: number;
    pwdLastSetAt: number;
    badPasswordTime: number;
    badPwdCount: number;
} | {
    objectGUID: string;
    whenCreated: number;
    username: string;
    firstName: string;
    name: string;
    language: string;
    userPassword: string;
    mail: string;
    emailVerified: boolean;
    mobile: string;
    mobileVerified: boolean;
    memberOf: string[];
    orgId: string;
    userAccountControl: number;
    pwdLastSet: number;
    whenChanged?: undefined;
    middleName?: undefined;
    pwdLastSetAt?: undefined;
    badPasswordTime?: undefined;
    badPwdCount?: undefined;
} | {
    objectGUID: string;
    whenCreated: number;
    username: string;
    firstName: string;
    name: string;
    language: string;
    userPassword: string;
    mail: string;
    emailVerified: boolean;
    mobile: string;
    mobileVerified: boolean;
    memberOf: string[];
    orgId: string;
    userAccountControl: number;
    pwdLastSet: number;
    pwdLastSetAt: number;
    whenChanged?: undefined;
    middleName?: undefined;
    badPasswordTime?: undefined;
    badPwdCount?: undefined;
})[];
export const roles: string[];
export const defaultRoles: string[];
